[project]
name = "ai-discord-lol"
version = "0.1.0"
description = "A Discord bot"
requires-python = "==3.10.*"
authors = [{ name = "lfsilva", email = "luis.fmsilva@hotmail.com" }]
dependencies = [
    "python-dotenv==0.21.0",
    "discord.py==2.3.2"
]

[project.optional-dependencies]
dev = []